# Generated by Django 3.1.6 on 2022-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20220612_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='utilisateur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
