# Generated by Django 3.1.6 on 2022-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20220612_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
