# Generated by Django 3.1.6 on 2022-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20220612_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='date_de_la_mises_a_jour',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
