# Generated by Django 3.1.6 on 2022-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20220612_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='date_de_la_mises_a_jour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
