# Generated by Django 3.1.6 on 2022-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_auto_20220612_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='date_de_la_mises_a_jour',
            field=models.DateField(),
        ),
    ]
