# Generated by Django 3.1.6 on 2022-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20220612_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicien', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
