# Generated by Django 3.1.6 on 2022-06-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_auto_20220613_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technicien',
        ),
    ]
